### ISSUE TITLE
[Documentation] Getting started instructions and Access Tokens

### ISSUE THREAD

**Issue by ArturoNereu** [huggingface/unity-api#10]
The Usage > Configuration section in the README says that to generate an API key, people need to go to https://huggingface.co/settings/profile

However, there's no option to generate API keys there, the correct link to generate the access tokens is: https://huggingface.co/settings/tokens

On that note, I suggest you rename the API key (in the README and the Hugging Face API Wizard) to Access Tokens. There are also the SSH and GPG keys which might yield confusion.

**Comment by dylanebert** [comment]
thanks :) link is updated
