### ISSUE TITLE
Multiple models

### ISSUE THREAD

**Issue by gFulvio** [huggingface/unity-api#13]
Really good job!
Is it possible to use more than one model for each task simultaneously?
Thank you.

**Comment by simoninithomas** [comment]
Hey there 👋 apologies I missed your issue. Yes you can:

```
using HuggingFace.API;

HuggingFaceAPI.TextToImage("a cat in a hat", result => {
    // Do something with the result, which in this case is a Texture2D
}, error => {
    // Handle errors
    Debug.LogError(error);
});
```

You just need to call HuggingFaceAPI multiple time

**Comment by gFulvio** [comment]
What I mean is to use text generation with two models, a Bart and a gpt in the same environment. How can I do this?
