### ISSUE TITLE
[FEATURE REQUEST] Run Models Locally

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/unity-api#20]
Hi,
Thanks for making the great tutorial (on Substack)!
Might it be possible to allow users to run models locally (instead of using the API), and bundle the models into their apps? This would be great for offline usage.
Thank you!

**Comment by simoninithomas** [comment]
Hey there 👋 , yes it's possible but not with this plugin but with Sentis and Hugging Face Sharp Transformers
