### ISSUE TITLE
Missing Image to Image and Text/Image to Image

### ISSUE THREAD

**Issue by yosun** [huggingface/unity-api#3]
For example... Controlnet

**Comment by simoninithomas** [comment]
Hey there 👋. I'm a new maintainer of the repo. 
We don't plan for now to add Image to Image in the Unity plugin.

**Comment by yosun** [comment]
hmm you're also missing out on not including image to 3D https://twitter.com/Yosun/status/1721892003041149434

**Comment by simoninithomas** [comment]
Sorry I wasn't clear, what I mean is that we don't plan to do it ourselves in the Unity plugin but since it's an open source plugin people can contribute and add this feature.

For now we focus on LLM, STT and TTS. But people can contribute and we are pleased to merge PR 🤗

**Comment by StephenHodgson** [comment]
I support it in my plugin: https://github.com/RageAgainstThePixel/com.rest.huggingface
