### ISSUE TITLE
Increase default max timeout value

### ISSUE THREAD

**Issue by 2600th** [huggingface/unity-api#4]
TextToImageExample is failing with the current setting increasing the timeout fixes the generation.

**Comment by simoninithomas** [comment]
Hey there 👋 . I'm the new maintainer of the project.

Thanks for your feedback. I'm adding it to the roadmap of the plugin we plan to make this roadmap public in the upcoming weeks 🤗

**Comment by simoninithomas** [comment]
Hey there 👋 Max timeout is now implemented. You can add it in the wizard:

![image](https://github.com/huggingface/unity-api/assets/13088472/0fe983a9-72f4-417a-b8df-add8f0c3ee60)
